Plastic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^', include("doctor.urls")),
    url(r'^', include("articles.urls")),
    url(r'^', include("main_pages.urls")),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.conf.urls import url

from .views import doctor_detail, service_detail, stock_list, under_detail, doctor_list, review_list, review_detail
from main_pages.views import all_forms

urlpatterns = [
    url(r'^doctor/(?P<slug>[-\w]+)/$', all_forms(doctor_detail), name='doctor_detail'),
    url(r'^uslugi/(?P<slug>[-\w]+)/$', all_forms(service_detail), name='service_detail'),
    url(r'^uslugi/(?P<service>[-\w]+)/(?P<under_slug>[-\w]+)/$', all_forms(under_detail), name='under_detail'),
    url(r'^akcii/$', all_forms(stock_list), name='stock_list'),
    url(r'^vrachi/$', all_forms(doctor_list), name='doctor_list'),
    url(r'^otzivi/$', all_forms(review_list), name='review_list'),
    url(r'^otzivi/(?P<slug>[-\w]+)/$', all_forms(review_detail), name='review_detail'),
]

doctor/models.py
### -*- coding: utf-8 -*- ###
from __future__ import unicode_literals
from django.db import models
from redactor.fields import RedactorField
from django.urls import reverse
from datetime import date

from articles.models import ArticleCategory


class Doctor(models.Model):
    name = models.CharField(max_length=200, verbose_name='Имя')
    title = models.CharField(max_length=200, blank=True)
    slug = models.SlugField(unique=True)
    keywords = models.CharField(max_length=1024, blank=True)
    description = models.CharField(max_length=1024, blank=True)
    image = models.ImageField(null=True, blank=True, verbose_name='Фото')
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name='Создано')
    special = models.CharField(max_length=200, verbose_name='Специализация', blank=True, null=True)
    experience = models.CharField(max_length=200, verbose_name='Стаж', blank=True, null=True)
    category = models.CharField(max_length=200, verbose_name='Категория', blank=True, null=True)
    content = RedactorField(verbose_name='Контент')

    class Meta:
        verbose_name = 'Врача'
        verbose_name_plural = 'Врачи'

    def __str__(self):  # For Python 2, use __unicode__ too
        return self.slug

    def get_absolute_url(self):
        return reverse('doctor_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        try:
            this_record = Doctor.objects.get(id=self.id)
            if this_record.image != self.image:
                this_record.image.delete(save=False)
        except:
            pass
        super(Doctor, self).save(*args, **kwargs)


class Service(models.Model):
    header_one = models.CharField(max_length=200, verbose_name='Заголовок')
    header_two = models.CharField(max_length=200, blank=True, verbose_name='Подзаголовок')
    doctor = models.ManyToManyField(Doctor, verbose_name='Врачи')
    service_category = models.ForeignKey(ArticleCategory, default=1, verbose_name='Категория')
    image = models.ImageField(verbose_name='Изображение', blank="True")
    menu_name = models.CharField(max_length=200, verbose_name='В Меню', help_text='Название в меню сайтбара',
                                 default='Услуга')
    title = models.CharField(max_length=200, blank=True)
    slug = models.SlugField(unique=True)
    keywords = models.CharField(max_length=1024, blank=True)
    description = models.CharField(max_length=1024, blank=True)
    advt = models.CharField(max_length=141, blank=True, verbose_name='Анонс', help_text='Ограничено 141 символом')
    content = RedactorField(verbose_name='Контент')

    class Meta:
        verbose_name = 'Услугу'
        verbose_name_plural = 'Услуги'

    def __str__(self):  # For Python 2, use __unicode__ too
        return self.header_one

    def get_absolute_url(self):
        return reverse('service_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        try:
            this_record = Service.objects.get(id=self.id)
            if this_record.image != self.image:
                this_record.image.delete(save=False)
        except:
            pass
        super(Service, self).save(*args, **kwargs)


class Stock(models.Model):
    service = models.ManyToManyField(Service, verbose_name='Услуги', blank=True)
    #under_service = models.ManyToManyField('UnderService', blank=True, verbose_name='Подслуги')
    title = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(verbose_name='Изображение', blank=True, null=True)
    period = models.DateField(verbose_name='Срок действия', default=date.today, blank=True, null=True)
    content = RedactorField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Акцию'
        verbose_name_plural = 'Акции'

    def __str__(self):  # For Python 2, use __unicode__ too
        return self.title

    def save(self, *args, **kwargs):
        try:
            this_record = Stock.objects.get(id=self.id)
            if this_record.image != self.image:
                this_record.image.delete(save=False)
        except:
            pass
        super(Stock, self).save(*args, **kwargs)


class UnderService(models.Model):
    header_one = models.CharField(max_length=200, verbose_name='Заголовок')
    header_two = models.CharField(max_length=200, blank=True, verbose_name='Подзаголовок')
    service = models.ForeignKey(Service, verbose_name='Услуга')
    menu_name = models.CharField(max_length=200, verbose_name='В Меню', help_text='Название в меню сайтбара')
    title = models.CharField(max_length=200, blank=True)
    slug = models.SlugField(unique=True)
    keywords = models.CharField(max_length=1024, blank=True)
    description = models.CharField(max_length=1024, blank=True)
    content = RedactorField(verbose_name='Контент')

    class Meta:
        verbose_name = 'Подуслугу'
        verbose_name_plural = 'Подуслуги'

    def __str__(self):  # For Python 2, use __unicode__ too
        return self.header_one

    def get_absolute_url(self):
        return reverse('under_detail', kwargs={'under_slug': self.slug, 'service': self.service.slug})


class Review(models.Model):
    doctor = models.ManyToManyField(Doctor, verbose_name='Врач', blank=True)
    header = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=200, verbose_name='Имя', blank=True)
    image = models.ImageField(verbose_name='Изображение', blank=True)
    content = RedactorField(verbose_name='Контент', blank=True)
    answer = RedactorField(verbose_name='Ответ', blank=True)
    doctor_answer = models.CharField(max_length=200, verbose_name='Имя', help_text='Имя ответчика', blank=True)
    title = models.CharField(max_length=200, blank=True)
    keywords = models.CharField(max_length=1024, blank=True)
    description = models.CharField(max_length=1024, blank=True)

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

    def __str__(self):  # For Python 2, use __unicode__ too
        return self.header

    def get_absolute_url(self):
        return reverse('review_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        try:
            this_record = Review.objects.get(id=self.id)
            if this_record.image != self.image:
                this_record.image.delete(save=False)
        except:
            pass
        super(Review, self).save(*args, **kwargs)


class History(models.Model):
    header = models.CharField(max_length=200, verbose_name='Заголовок')
    title = models.CharField(max_length=200, blank=True)
    history_service = models.ForeignKey(Service, verbose_name='Услуга')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение', blank=True)
    advt = models.TextField(max_length=300, blank=True, verbose_name='Анонс на главной',
                            help_text='Ограничено 300 символами')
    keywords = models.CharField(max_length=1024, blank=True)
    description = models.CharField(max_length=1024, blank=True)
    content = RedactorField(verbose_name='Контент')

    class Meta:
        verbose_name = 'Историю'
        verbose_name_plural = 'Истории'

    def __str__(self):  # For Python 2, use __unicode__ too
        return self.slug

    def get_absolute_url(self):
        return reverse('history_detail', kwargs={'his_slug': self.slug})

    def save(self, *args, **kwargs):
        try:
            this_record = History.objects.get(id=self.id)
            if this_record.image != self.image:
                this_record.image.delete(save=False)
        except:
            pass
        super(History, self).save(*args, **kwargs)

main_pages/forms.py
from django import forms


class CallForm(forms.Form):
    tel = forms.CharField(required=True, max_length=14)
    name = forms.CharField(required=True, max_length=50)
    accept = forms.BooleanField(required=True)


class MessageForm(forms.Form):
    mes_tel = forms.CharField(required=True, max_length=14)
    mes_name = forms.CharField(required=True, max_length=50)
    mes_message = forms.CharField(required=True, max_length=360)
    mes_accept = forms.BooleanField(required=True)


class FileForm(forms.Form):
    f_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'ФИО'}), required=True, max_length=50)
    f_mail = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}), required=True)
    f_message = forms.CharField(widget=forms.Textarea(attrs={'rows': '4', 'cols': '30'}), required=True, max_length=300)
    f_file = forms.FileField(widget=forms.FileInput, required=False)
    f_news = forms.BooleanField(widget=forms.CheckboxInput(check_test=lambda value: True, attrs={'value': 'a1'}), required=False)
    f_accept = forms.BooleanField(widget=forms.CheckboxInput(attrs={'value': 'a5'}), required=True)

templates/base.html
{% load staticfiles %}
{% load main_menu %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{%block description %}{% endblock description %}">
    <meta name="keywords" content="{%block keywords %}{% endblock keywords %}">
    <link rel="icon" href="{% static 'img/d_icon.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/d_icon.png' %}">
    <title>{%block title%}Клиника Долголетие{%endblock title%}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.min.css' %}">
    {% block head %}{%endblock head %}
    <!--[if IE]>
		<style type="text/css">
			.title_color-1 {
				color: #d8b06e;
				background: none;
			}

			.
		</style>
		<![endif]-->
</head>
<body>
{% block container %}<div class="container-main no-scroll">{% endblock container %}
<header class="header-main no-scroll">
    <div class="container">
        <div class="grid-row clearfix top_head">
            <div class="left_head">
                <a href="{% url 'index' %}" class="logo"><img src="{% static 'img/logo.png' %}" alt="logo" /></a>
			</div>
			<div class="right_head">
                <div class="content_right_head clearfix">
                    <div class="con_contacts">
                        <a href="tel:+78126710170" class="con_phone"><span>+7 (812)</span> 671-01-70</a><br>
                        <div class="con_time"><span>ежедневно 9:00 - 21:00</span></div>
                        <div class="block_soc">
                            <a href="https://vk.com/plastikame" target="_blank"><img src="{% static 'img/vk.png' %}" alt="pic" /></a>
                            <a href="https://www.instagram.com/plastika.me/" target="_blank"><img src="{% static 'img/inst.png' %}" alt="pic" /></a>
                            <a href="https://www.facebook.com/%D0%94%D0%BE%D0%BB%D0%B3%D0%BE%D0%BB%D0%B5%D1%82%D0%B8%D0%B5-%D0%9E%D1%82%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%9F%D0%BB%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B9-%D0%A5%D0%B8%D1%80%D1%83%D1%80%D0%B3%D0%B8%D0%B8-1697615780541427/" target="_blank"><img src="{% static 'img/facebook.png' %}" alt="pic" /></a>
                        </div>
                    </div>
                    <div class="con_adress">
                        <p>Санкт-Петербург, ст. м. «Горьковская», улица Малая Посадская, д. 7/4</p>
                    </div>
                    <div class="con_head_feedback">
                        <ul class="head_feedback_list">
                            <li class="head_feedback_item feedback__enroll"><a href="#" class="btn_write_open">Записаться</a></li>
                            <li class="head_feedback_item feedback__call"><a href="#" class="btn_call_open">Заказать звонок</a></li>
                            <li class="head_feedback_item feedback__letter"><a href="#" class="btn_mail_open">Написать нам</a></li>
                            <li class="head_feedback_item feedback__consultation-sk"><a href="skype:Plastika.me">Консультация в Skype</a></li>
                        </ul>
                    </div>
                </div>
			</div>
			<div class="con_adress2"><p>Санкт-Петербург, ст. м. «Горьковская», улица Малая Посадская, д. 7/4</p></div>
		</div>
		{% get_main_menu mainmenu %}
	</div>
</header>
{% block header_fixed %}{% endblock %}
{% block content %}
{%endblock content %}
    </div>
    <div class="hidden">
        <form id="hidden_form" role="form" method="post" action=" ">
            {% csrf_token %}
            <div class="close_hidden_form">×</div>
            <h2>Заказать звонок</h2>
            <label for="id_tel"><input class="input1" type="tel" name="tel" placeholder="Ваш телефон" required/></label>
    		<label for="id_name"><input class="input1" type="text" name="name" placeholder="Ваше имя" required/></label>
            <span class="wrapper_checkbox">
                <input type="checkbox" name="accept" id="checkbox2" value="a2" required>
                <label for="checkbox2"></label>
                <strong>Я даю согласие на обработку <a href="http://www.plastika.me/politika-konfidencialnosti/"><u>персональных данных</u></a></strong>
            </span>
    		<button class="button" type="submit">Отправить</button>
    	</form>
    </div>
    <div class="hidden2">
        <form id="hidden_form2" class="hidden_form2" role="form" method="post" action=" ">
            {% csrf_token %}
            <div class="close_hidden_form">×</div>
            <h2>Написать нам</h2>
            <label><input class="input1" type="tel" name="mes_tel" placeholder="Ваш телефон" required/></label>
            <label><input class="input1" type="text" name="mes_name" placeholder="Ваше имя" required/></label>
            <label><textarea  class="input1" name="mes_message" id="textarea_form" rows="5" placeholder="Cообщение"></textarea></label>
            <span class="wrapper_checkbox">
                <input type="checkbox" name="mes_accept" id="checkbox3" value="a3" required>
                <label for="checkbox3"></label>
                <strong>Я даю согласие на обработку <a href="http://www.plastika.me/politika-konfidencialnosti/"><u>персональных данных</u></a></strong>
            </span>
            <button class="button" type="submit">Отправить</button>
        </form>
    </div>
    <div class="hidden3">
        <form class="hidden_form2" role="form" method="post" action=" ">
            {% csrf_token %}
            <div class="close_hidden_form">×</div>
            <h2>Записаться</h2>
            <label><input class="input1" type="tel" name="mes_tel" placeholder="Ваш телефон" pattern="[0-9]{6,20}" title="Только цыфры. Пример: 78126710170" required/></label>
            <label><input class="input1" type="text" name="mes_name" placeholder="Ваше имя" /></label>
            <label><textarea  class="input1" name="mes_message" rows="5" placeholder="Cообщение"></textarea></label>
            <span class="wrapper_checkbox">
                <input type="checkbox" name="mes_accept" id="checkbox4" value="a4" required>
                <label for="checkbox4"></label>
                <strong>Я даю согласие на обработку <a href="http://www.plastika.me/politika-konfidencialnosti/"><u>персональных данных</u></a></strong>
            </span>
            <button class="button" type="submit">Отправить</button>
        </form>
    </div>
    <script src="{% static 'js/app.min.js' %}"></script>
    <!-- Yandex.Metrika counter --> <script type="text/javascript" > (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter41206394 = new Ya.Metrika({ id:41206394, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/41206394" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
</body>
</html>

templates/footer.html
{% load main_menu %}
{% load staticfiles %}
<footer class="footer-main">
    <div class="line-deco line-deco_big  line-deco_absolute-top"></div>
    <div class="container">
        <div class="footer_content clearfix">
            <div class="left">
                {% get_footer_menu %}
            </div>
            <div class="center">
                <div class="forum_footer">
                    <p class="forum_title">Форум</p>
                    <div class="forum_item">
                        <p><a href="http://forum.spina.spb.ru/topic5.html">Блефаропластика</a></p>
                        <span>admin</span>
                        <span class="date">09 декабря; 16:15</span>
                    </div>
                    <div class="forum_item">
						<p><a href="http://forum.spina.spb.ru/topic31.html">Полипы в носу</a></p>
						<span>admin</span>
						<span class="date">22 февраля; 02:23</span>
					</div>
					<div class="forum_item">
						<p><a href="http://forum.spina.spb.ru/topic870.html">Исправление формы носа</a></p>
						<span>admin</span>
						<span class="date">04 июля; 16:20</span>
					</div>
                    <div class="wrapper_forum_button">
                        <a href="http://forum.spina.spb.ru" class="forum_btn">Перейти на форум</a>
                    </div>
                </div>
                <div class="adress_footer">
                    <p class="adress_title">Наш адрес</p>
                    <p class="map_address">
                        <img src="{% static 'img/map.png' %}" alt="pic" />Санкт-Петербург,<br>ст. м. «Горьковская»,<br>улица Малая Посадская, д. 7/4</p>
                    <p class="phone_footer">
                        <img src="{% static 'img/callf.png' %}" alt="pic" />
                        <a href="tel:78126710170"><span>+7 (812)</span>671-01-70</a>
                    </p>
                    <p class="grafic_footer">ежедневно 9:00 - 21:00</p>
                </div>
            </div>
            <div class="right">
                <div class="social_footer">
                    <p class="social_title">Мы в соцсетях</p>
                    <div class="social_list">
                        <a href="https://vk.com/plastikame" target="_blank" class="social_link"><img src="{% static 'img/vk.png' %}" alt="pic" /></a>
                        <a href="https://www.instagram.com/plastika.me/" target="_blank" class="social_link"><img src="{% static 'img/inst.png' %}" alt="pic" /></a>
                        <a href="https://www.facebook.com/%D0%94%D0%BE%D0%BB%D0%B3%D0%BE%D0%BB%D0%B5%D1%82%D0%B8%D0%B5-%D0%9E%D1%82%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%9F%D0%BB%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B9-%D0%A5%D0%B8%D1%80%D1%83%D1%80%D0%B3%D0%B8%D0%B8-1697615780541427/" target="_blank" class="social_link"><img src="{% static 'img/facebook.png' %}" alt="pic" /></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/footer_menu.html
<ul class="footer_menu">
    {% for item in f_menu %}
	<li class="footer_menu__item"><a href="{{ item.url }}">{{ item.menu_name }}</a></li>
	{% endfor %}
</ul>

templates/main_menu.html
{% load staticfiles %}
<div class="grid-row grid-row_justify grid-row_middle menu-main">
    {% for m in m_menus %}
    <div class="grid-row__col menu-main__item"><a href="{{ m.url }}">{{ m.menu_name }}</a></div>
    <div class="grid-row__col delimiter-v-line"></div>
	{% endfor %}
    <div class="grid-row__col menu-main__item search">
        <a href=""><img src="{% static 'img/soprano/search.png' %}" alt="icon" /></a>
    </div>
	<div class="line-deco line-deco_absolute-bottom"></div>
    <div class="block_search">
        <form action="{% url 'service_search' %}" method="get">
            <button class="btn_search" type="submit"></button>
            <input class="input2" type="text" name="s" placeholder="Поиск по сайту" value="{{ request.GET.s }}">
        </form>
    </div>
</div>
<div class="mobile_menu-main">
    <div class="hamburger_menu"><span>Меню</span></div>
		<ul class="mobile_menu_list">
	    {% for m in m_menus %}
			<li class="mobile_menu_item"><a href="{{ m.url }}">{{ m.menu_name }}</a></li>
		{% endfor %}
		</ul>
    <div class="mobile_search">
        <div class="delimiter-v-line"></div>
        <div class="menu-main__item search">
            <a href="#"><img src="{% static 'img/soprano/search.png' %}" alt="icon" /></a>
        </div>
    </div>
    <div class="block_search">
        <form action="{% url 'service_search' %}" method="get">
            <button class="btn_search" type="submit"></button>
            <input class="input2" value="{{ request.GET.s }}" autocomplete="off" type="text" name="s" placeholder="Поиск по сайту">
        </form>
    </div>
	<div class="line-deco line-deco_absolute-bottom"></div>
</div>

templates/main_slider.html
{% load static %}
<div class="header_slider_wrap">
    <div class="triangle_left"></div>
	<div class="triangle_right"></div>
	<div class="header_slider">
	    {% for sl in main_slider %}
		<div class="header_slider_item" style="background: url({% if sl.image  %}{{ sl.image.url }}{% else %}{% static 'img/bg_slider.png' %}{% endif %}) no-repeat;">
			<div class="container">
				<div class="slider_description">
					<h2 class="slider_title">{{ sl.title }}</h2>
					<p class="slider_text">{% autoescape off %}{{sl.content}}{% endautoescape %}</p>
					{% if not sl.button == None %}
					<div class="wrap_slider_button">
						<a href="{{ sl.button}}" class="btn_slide__link">Подробнее</a>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>

templates/page_slider.html
{% load staticfiles %}
<div class="left_slider">
    <div class="left_slider_list">
        {% for slide in page_slider %}
        <div class="left_slider_item">
			<div class="wrap_img">
			    <img src="{% if slide.image %}{{ slide.image.url }}{% else %}{% static 'img/soprano/face_slide.png' %}{% endif %}" alt="face" />
			</div>
			<div class="wrap_text">
				<p class="title_cart_slide">{{ slide.title }}</p>
				<p class="descr_cart_slide">{{ slide.text }}</p>
			</div>
		</div>
    	{% endfor %}					
	</div>
</div>